#!/bin/bash
SCRIPTDIR=$(cd $(dirname $0) && pwd)
function prependDirToLuaPath() {
	dir=$1
	export LUA_PATH_EXTRA="${dir}?:${dir}?.lua:${dir}?/init.lua:${LUA_PATH_EXTRA}"
}

#prependDirToLuaPath "${SCRIPTDIR}/lua-feedparser/"
#prependDirToLuaPath "${SCRIPTDIR}/mk/src/"
#prependDirToLuaPath "${SCRIPTDIR}/"
#echo "LUA_PATH_EXTRA is ${LUA_PATH_EXTRA}"
#  -e "package.path = os.getenv('LUA_PATH_EXTRA') .. package.path"
lua -lluarocks.loader "${SCRIPTDIR}/main.lua"
